# 理论上 IngressClass 下定义的字段，放到 .Values .Values.global 中也是可以生效的
# 定义 Context 需使用 `{{- $_ := set . "Context" .Values.IngressClass }}`

IngressClass:
  annotations: {}
  labels: {}
  # name fullname 功能一致，但 fullnane 会覆盖 name
  # 优先级 fullname > name
  name: string
  fullname: string
  namespace: string
  controller: string
  parameters:
    apiGroup: string
    kind: string
    name: string
    namespace: string
    scope: string
